name: PHPMND

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  phpmnd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Install PHPMND
        run: composer global require povils/phpmnd:^3.0 --no-interaction --no-progress

      - name: Run PHPMND
        run: ~/.composer/vendor/bin/phpmnd app routes tests --exclude=database --hint
