name: phpunit

on:
  pull_request:
  push:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: |
          cp .env.example .env
          php artisan key:generate
      - run: vendor/bin/phpunit
